CREATE TABLE [dbo].[Athlete]
(
	[AID] INT IDENTITY (1,1) NOT NULL,
	[FirstName] NVARCHAR(1028) NOT NULL,
	[LastName] NVARCHAR(1028) NOT NULL,
	[Gender] NVARCHAR(1028) NOT NULL,
	CONSTRAINT[PK_dbo.Athlete] PRIMARY KEY CLUSTERED([AID] ASC)
);